# Generated by Django 3.2.5 on 2021-07-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210715_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='statu',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
