# Generated by Django 3.2.5 on 2021-07-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210715_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='statu',
            new_name='borowingStatu',
        ),
    ]
