# Generated by Django 3.2.5 on 2021-07-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borowingStatu',
            field=models.CharField(choices=[('Available', 'Available'), ('Un available', 'Un available')], max_length=20),
        ),
    ]
